Render custom configs that don't have a default template
wiwdata/presto-chart pull request #3
Opened 2019-11-06 12:43 UTC by sbrunk

If we have s.th. like
```yaml
coordinatorConfigs:
  access-control.properties: |
    access-control.name=read-only
```
in our helm values, it's not added to the configuration right now, because there's no matching default template in the docker image.

This is an attempt to allow rendering of custom config files/templates, similar to how it's done with catalogs already.

2019-11-07 14:30 UTC, sernst requested changes
Thanks for another good addition! Just a few PEP 8 style compliance issues to adjust before these changes are ready to merge.

2019-11-07 14:30 UTC, sernst commented on image/presto-entrypoint.py
> +    ## Render custom configs that don't have a default template
[PEP 8 block comment](https://www.python.org/dev/peps/pep-0008/#id31) format:

```suggestion
    # Render custom configs that don't have a default template
```

2019-11-07 14:30 UTC, sernst commented on image/presto-entrypoint.py
> +    default_config_names = {
[PEP 8 maximum line length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) Maybe something like:

```python
    default_directory = Path(TEMPLATE_DEFAULT_DIRECTORY)
    default_config_names = {
        path.stem 
        for path in default_directory.glob("*.properties.jinja2")
    }
```

instead?

2019-11-07 14:30 UTC, sernst commented on image/presto-entrypoint.py
> +    for custom_config_path in Path(TEMPLATE_CUSTOM_DIRECTORY).glob("*.properties"):
[PEP 8 maximum line length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) Maybe something like:

```python
    custom_directory = Path(TEMPLATE_CUSTOM_DIRECTORY)
    for path in custom_directory.glob("*.properties"):
        if path.name not in default_config_names:
            render(
                template_name=str(path.relative_to(Path(TEMPLATE_DIRECTORY))),
                output_directory=CONFIGS_DIRECTORY,
                **arguments
            )
```

instead?

2019-11-08 08:35 UTC, sbrunk commented
Ah thanks, I guess I should have enabled the linter. :)

2019-11-13 03:32 UTC, sernst approved these changes
Looks good!

2019-11-13 03:32 UTC, merged